USE operation_support;

DROP TABLE  IF EXISTS db_log;

CREATE TABLE  db_log
( log_id             	INT NOT NULL 	AUTO_INCREMENT 
, connection_id   		INT UNSIGNED 	NOT NULL DEFAULT 0
, mysql_login_name      VARCHAR(64) 	NOT NULL DEFAULT 'unknown'
, log_type			    VARCHAR(50)
, log_message			VARCHAR(2000)
, login_ts       		DATETIME 		NOT NULL DEFAULT CURRENT_TIMESTAMP
, PRIMARY KEY (log_id,login_ts) 
)
	PARTITION BY RANGE( YEAR(login_ts) ) 
	SUBPARTITION BY HASH( MONTH(login_ts) ) SUBPARTITIONS 12  
  ( 
	 PARTITION p_2018 VALUES LESS THAN (2019)
    ,PARTITION p_2019 VALUES LESS THAN (2020)
	,PARTITION p_2020 VALUES LESS THAN (2021)
	,PARTITION p_2021 VALUES LESS THAN (2022)
	,PARTITION p_2022 VALUES LESS THAN (2023)
	,PARTITION p_max VALUES LESS THAN MAXVALUE  
  ); 
