
#! /bin/python

# Script to cross check hive tables between clusters
# 'output' is generated by row_counts.sh

# Upload text files (cluster 1 should be source of truth)
cluster_1_output = raw_input('Path to cluster_1_output:')
cluster_2_output = raw_input('Path to cluster_2_output:')
cluster_1 = open(cluster_1_output, 'r').read()
cluster_2 = open(cluster_2_output, 'r').read()

# Create lists from text files
cluster_1_list = cluster_1.split('\n')
cluster_2_list = cluster_2.split('\n')

# Compare second list to the first
print [x for x in cluster_1_list if x not in cluster_2_list]
